default: &default
  adapter: postgresql
  user: kevinmccarthy
  password: password
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gameorganiser_development

test:
  <<: *default
  database: gameorganiser_test

